/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    getArea
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_Main_getArea
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
