/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    printInt
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Main_printInt
  (JNIEnv *, jclass, jint);

/*
 * Class:     Main
 * Method:    printByte
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_Main_printByte
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     Main
 * Method:    printChar
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_Main_printChar
  (JNIEnv *, jclass, jchar);

/*
 * Class:     Main
 * Method:    printShort
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_Main_printShort
  (JNIEnv *, jclass, jshort);

/*
 * Class:     Main
 * Method:    printLong
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Main_printLong
  (JNIEnv *, jclass, jlong);

/*
 * Class:     Main
 * Method:    printFloat
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_Main_printFloat
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     Main
 * Method:    printDouble
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_Main_printDouble
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     Main
 * Method:    printBoolean
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_Main_printBoolean
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
