/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    print2DIntArr
 * Signature: ([[I)V
 */
JNIEXPORT void JNICALL Java_Main_print2DIntArr
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     Main
 * Method:    make2DIntArr
 * Signature: (II)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_Main_make2DIntArr
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
